### ISSUE TITLE
Min and Max text doesn't change to a number

### ISSUE THREAD

**Issue by bhuvneshvarma** [anothem/android-range-seek-bar#15]
I see on left and right of seekbar text Min and Max is wiritten.
I have set          
mRangeSeekBar.setRangeValues(0, mp.getDuration()/1000);
 mRangeSeekBar.setSelectedMinValue(0);
mRangeSeekBar.setSelectedMaxValue(30);

but still the text Min and Max doesn't change to a number.How can i change it to range or can i remove it?

**Comment by anothem** [comment]
Min/Max labels do not change. You can set them and disable them with the "showLabels" property, or programmatically, but they do not change text value.

**Comment by bhuvneshvarma** [comment]
okay thanks..Can i change the colour of current thumb position on top of thumbms from white to some other colour?

**Comment by francisdidden** [comment]
I'm goning to jump in because my question is very similar and bhuvneshvarma seems to be experiencing the same "error" as I. I can't see the floating value above the sliders. I thought it was set visible by default but apparently something is going wrong.

I'm using gradle to sync you library and everyhing else works great.

Any help would be appreciated.
