### ISSUE TITLE
Is API15 really the min?

### ISSUE THREAD

**Issue by spyhunter99** [anothem/android-range-seek-bar#52]
I want to use thus with an api8 min project. :)

**Comment by anothem** [comment]
You can always include it in source, rather than as an AAR library, change the minApi and see if it works and/or fix any arising issues. But, the version of it that I am maintaining will not have "official" support for anything less than API 15. Unfortunately, I can barely get around to fixing issues for it as is. 
I personally haven't tried to run it on anything less, so don't know what sorts of issues will come up, if any at all.

**Comment by spyhunter99** [comment]
ok thanks for the info

**Comment by spyhunter99** [comment]
so i looked into this, the real api min is 11 without code modifications. api8 can be supported with some checks on api level for the shadows
