### ISSUE TITLE
Custom thumb image with min and max initialize with code

### ISSUE THREAD

**Issue by adamhongmy** [anothem/android-range-seek-bar#81]
How can I set absoluteMaxValue and absoluteMinValue via code? I refer to the sample, it only demos:

```
  // Setup the new range seek bar
        RangeSeekBar<Integer> rangeSeekBar = new RangeSeekBar<Integer>(this);
        // Set the range
        rangeSeekBar.setRangeValues(15, 90);
        rangeSeekBar.setSelectedMinValue(20);
        rangeSeekBar.setSelectedMaxValue(88);
        // Add to layout
        LinearLayout layout = (LinearLayout) findViewById(R.id.seekbar_placeholder);
        layout.addView(rangeSeekBar);
```

However, I have custom thumb for the seek bar and I would like to have this:

```
 RangeSeekBar rangeSeekBar  = (RangeSeekBar) findViewById(R.id.rangeSeekBar);
        rangeSeekBar.setRangeValues(15, 90);
        rangeSeekBar.setSelectedMinValue(20);
        rangeSeekBar.setSelectedMaxValue(88);
```

Obviously, I couldn't do this because it needed to call `RangeSeekBar<Integer>` instead. 
Therefore, is it a way to achieve this or any other solution?

**Comment by anothem** [comment]
I don't follow, what's the problem with the code you showed?

**Comment by adamhongmy** [comment]
I want to have custom thumb image with the ability to set min and max via code. Is that better to understand?

**Comment by adamhongmy** [comment]
or at least change the colour of the thumb and line.

**Comment by anothem** [comment]
That's clear, what I don't understand is what the problem is. Your code above should work just fine. 

` RangeSeekBar rangeSeekBar  = (RangeSeekBar) findViewById(R.id.rangeSeekBar);
   rangeSeekBar.setRangeValues(15, 90);
   rangeSeekBar.setSelectedMinValue(20);
   rangeSeekBar.setSelectedMaxValue(88);
`

The only issue is that it will raise a warning about an unchecked cast every time you set something. Alternatively, you could do this, so at least you have the warning in only one place and can suppress it there:
`RangeSeekBar<Integer> customRsb = (RangeSeekBar<Integer>) findViewById(R.id.customRsb);`

**Comment by adamhongmy** [comment]
Oh, ya I do get the warning. I thought I wasn't allowed to do this. So it okay to do so?

**Comment by anothem** [comment]
Yup, it works. Haven't figured out a good way of getting rid of the warning from the library, but you can always suppress it.
